# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo apt-get update
      - run: sudo apt-get install jq

      # Build api files, but do *not* push back to github.
      # Pushing back to github here could trigger additional builds, causing a loop.
      - run: make download
      - run: make api

  deploy:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - add_ssh_keys

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - run: sudo apt-get update
      - run: sudo apt-get install jq

      # Set git configuration so we can push back to github.
      - run: git config --global user.email "tedivm@tedivm.com"
      - run: git config --global user.name "Robert Hafner"
      - run: git config --global push.default simple

      # Build files *and* push back to github.
      - run: make deploy

workflows:
  version: 2
  commit:
    jobs:
      - build
  api:
    jobs:
      - deploy
    triggers:
      - schedule:
          cron: "0 0,6,12,18 * * *"
          filters:
            branches:
              only:
                - master
